### ISSUE TITLE
10.2 Icons changed again

### ISSUE THREAD

**Issue by anathemamask** [Shushuda/Mappy-Continued#11]
I tried to follow your directions from the previous issue, but either i'm blind or the changes are too minute for me to follow what exactly is changing between your image files, i could not get my head around it AT ALL.

Anyway here's the 10.2 image icons extracted from the .blp
![new-ObjectIconsAtlas](https://github.com/Shushuda/Mappy-Continued/assets/26660743/8a74f258-6dda-46d9-a555-8e42685f2f04)

**Comment by Shushuda** [comment]
Hi, thanks for trying tho, hahah! The changes are very small, just 3 icons changing sizes, colors and/or shape.

I'm not gonna lie, my health is still very bad, even more so, but I'm finally getting some treatment soon so hopefully it will help.

In the meantime, I will try to update the textures during my better moments. Shouldn't take too long, I hope. ^^

**Comment by Shushuda** [comment]
Done.
