### ISSUE TITLE
11.0.5 - Icons blinking and changing

### ISSUE THREAD

**Issue by rubybrowncoat** [Shushuda/Mappy-Continued#14]
There's some kind of blinking issue with the icons changing to other icons.

![image](https://github.com/user-attachments/assets/5e66a501-88ef-4861-a883-952de39b1384)
![image](https://github.com/user-attachments/assets/74f56e18-136f-45fc-9a1e-f9f2da3adace)

**Comment by Shushuda** [comment]
I will fix it in the following days. I'm currently down with Covid hahah

**Comment by Shushuda** [comment]
Done, will be on Curseforge shortly, but not tested as I need to get back to bed lmao

**Comment by rubybrowncoat** [comment]
Sending good vibes. A get well soon wish from this hub of gits.
