### ISSUE TITLE
New bug on DF Beta servers

### ISSUE THREAD

**Issue by Voxxel** [Shushuda/Mappy-Continued#6]
Maybe they changed the blip texture order once again as turning on either the bigger nodes or classic style turns the nodes to a new blue icon. Flashing is also altered with this change. I spotted that the Flashing function makes the new rare symbol to flash too.

I don't know if this is the final texture order for now but if it is, then maybe it's better to wait until the next build to avoid unnecessary work every time they change it. (If that is the case, actually, I'm not sure)

**Comment by Shushuda** [comment]
Oh wow, they did change the texture completely.

But look what they did, they enlarged them by default. So the enlarge option will no longer be needed, now I can reverse that and make a "tiny icon" option instead for those that prefer less clutter.

![image](https://user-images.githubusercontent.com/26089938/199733696-7bef8399-ee2f-424a-b636-75ff88195049.png)
![image](https://user-images.githubusercontent.com/26089938/199733772-ba876e1c-3b31-4f1f-998f-f2a793996004.png)

Yep, you're right, I will wait with that. It should be safe to replace the texture around a week before DF launches. They usually push some last files at that time, to be ready to flip the switch at midnight.

**Comment by Shushuda** [comment]
You bet I will, I took 2 weeks off for DF :D

**Comment by Voxxel** [comment]
Good for you, I'm jealous, I only got 3 days off. :/

**Comment by Shushuda** [comment]
Tbh I'd rather have just a week off as always, but Polish law is weird. The employer is required to provide 2 weeks of undisturbed time off (including regular days off like holidays and weekends, it just needs to add up to 2 weeks not-in-work), which in practice means the salaried employee is required to take 2 weeks off. Otherwise the employer can send them on obligatory unpaid leave just to provide those 2 weeks and avoid being fined.
Feels like a waste of paid time off most of the time, but dura lex sed lex.

**Comment by Shushuda** [comment]
They're using these new textures in the phase 2 of the prepatch. Fixing now, new release should be ready today.

**Comment by Voxxel** [comment]
very nice of you, thank you!
Yea, it's strange they let all the weird beta coding stuff out into live.

**Comment by Shushuda** [comment]
It's very strange and annoying. Another big batch of addons stopped working now, I need to fix and shuffle my UI again, the chat window still doesn't remember its sizing and position and randomly snaps to the middle of the screen and becomes uber tiny after each relog... I can't imagine the chaos in the Blizz dev team right now, they must be crunching hard right now to fix this mess. Holy moly is this prepatch annoying lol

**Comment by Shushuda** [comment]
Btw, you might need to untick "small gathering nodes" option. It used to be Large, but default size is now large, so I reversed the behaviour of that option. If you had Large ticked, then Small will also be ticked in the new release.

**Comment by Shushuda** [comment]
Done, will be available on CF in up to an hour.

**Comment by Voxxel** [comment]
I hope they won't fix all the codes by reverting them so addon authors' work will not be in vain.

Anyway, thanks a lot, Shushuda for your time. Very much appreciated. <3
