### ISSUE TITLE
10.1: new icon-map

### ISSUE THREAD

**Issue by Voxxel** [Shushuda/Mappy-Continued#9]
Hi there, 
The new major patch has brought a new new icon map blip so the icons are messed up for now. Could you please fix it, Shushuda?

**Comment by Shushuda** [comment]
Hi, I'm on it. New release should be ready today.

**Comment by Shushuda** [comment]
Done, but I didn't test it lmao. My health issues kinda got 10x worse despite treatment, I'm too tired to check. :'>
I'm uploading to Curseforge now.

**Comment by Voxxel** [comment]
Looks perfect! Thank you! <3
I hope you're getting well soon, Weronika!
